version: '3'
services:
  api:
    container_name: 'api'
    image: 'mockoon/cli:latest'
    restart: 'unless-stopped'
    command: '--data /data --port 3000'
    volumes:
      - type: 'bind'
        source: './data.json'
        target: '/data'
    networks:
      - 'cloudflared'
    ports:
      - '3000:3000'
    depends_on:
      - 'tunnel'
 
  tunnel:
    container_name: 'tunnel'
    image: 'cloudflare/cloudflared:latest'
    restart: 'on-failure'
    command: 'tunnel --no-autoupdate run --token eyJhIjoiZGQ4YjdmZmU4YjUwMzA4NzBlNmJmYTljNDNkZjJkYzEiLCJ0IjoiNDI3MTQwZTEtN2YyMC00YWQ5LThjNWItYWYwNjBkYWRiNjMxIiwicyI6IlkyUXhabU00WVRjdE5UVTRaQzAwT0dNMExUZ3pZbU10TUdFeFpUUTVNMlkyTkRKaSJ9'
    environment:
      - 'TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query'
    networks:
      - 'cloudflared'
 
networks:
  cloudflared:
    name: 'cloudflared'









