#:schema node_modules/wrangler/config-schema.json
name = "worker-get-put-d1"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]


#[[d1_databases]]
#binding = "DB"
#database_name = ""
#database_id = ""

